import fs from "fs";
const FILE = new URL("../index.html", import.meta.url).pathname;
let src = fs.readFileSync(FILE, "utf8");

// v0.48 §4 — ZONE 1 becomes one plain-language sentence per building. Every number
// that used to live in these strings is now generated by effectLines() from the same
// fields computeRates()/computeCaps() read.
const EFFECT = {
  manaWell: "A steady trickle of mana, and somewhere to keep it.",
  farmstead: "Provisions, at whatever pace the season allows.",
  lumberMill: "Makes every woodcutter better at the job — and every saw in the Workshop raises that figure again.",
  mine: "Makes every miner better at the job.",
  quarry: "Makes every miner better at the job, considerably.",
  shelter: "Room for more wanderers, and somewhere to rest between expeditions.",
  longhouse: "Room for one more wanderer, and somewhere to rest between expeditions.",
  bardsHearth: "Culture, and a ceiling to hold it. Bards need an audience, so the output rises with the settlement.",
  poroPasture: "Poros, slowly. Their company makes a meal go further, so the settlement eats less.",
  tavern: "Takes the edge off overcrowding. Diminishing, and it can never remove crowding entirely.",
  skyrise: "Room for more wanderers without spending more ground.",
  storehouse: "The settlement's first real larder and lumber yard.",
  warehouse: "Dry, guarded and rat-proof — for materials, not meals.",
  harbor: "Bilgewater hulls at anchor hold more than any cellar.",
  archive: "Somewhere to keep what you know, and scholars who gather it faster.",
  academy: "A larger hall, a faster argument, and a wider ceiling on both.",
  observatory: "The sky turns out to be a great deal of knowledge, once you can hold it.",
  hexLab: "The deepest research the settlement can house.",
  forge: "Turns ore and mana into steel, continuously, while it is switched on.",
  tradeDock: "Every caravan comes back heavier. Diminishing, into the same pool as the Hexgate.",
  refinery: "Turns mana and ore into Hextech Crystals, and gives them somewhere to sit.",
  workshop: "Every craft in the Workshop returns more per action.",
  hunterLodge: "Every camp in the Wilds brings back more.",
  trainingGround: "Somewhere to hold Vigor and to earn a name — and Vigor accrues faster.",
  sumpMine: "Turns ore and mana into Zaun Ore, and gives it somewhere to sit.",
  coalgasVent: "Turns timber, steel and mana into Coalgas, and gives it somewhere to sit.",
  hexQuarry: "Turns ore, gold and mana into Hexcrystal Ore, and gives it somewhere to sit.",
  chembarrel: "Drives the three Zaun extractors harder. Diminishing, into the same pool as the two Sump upgrades.",
  hextechFoundry: "Raises everything the settlement produces — and every Hexdraulic Plant amplifies it further.",
  hexdraulicPlant: "Makes every Hextech Foundry more effective.",
  arcaneReactor: "Raises everything the settlement produces.",
  piltoverSpire: "Culture, and a ceiling to hold it.",
  vault: "Somewhere to put what the Sump brings up.",
  bloomery: "Turns ore and timber into steel, and gives it somewhere to sit.",
  augmentChamber: "Makes every tinkerer substantially better at the job.",
  hexgateBuilding: "Every caravan comes back heavier — diminishing, into the same pool as the Trade Docks — and crystals gain a far wider ceiling.",
  wardOfWatchers: "True Ice, a ceiling for Void Essence, and a lift to everything the settlement produces.",
  watchersEye: "A wider culture ceiling. Unlocks the Poro sacrifice — Poros become Poro Tears. Poros no longer pay morale, so the Eye has an uncontested claim on them.",
  frostguardCairn: "The Freljord monument line — every pasture's poros come faster.",
  avarosanHold: "The Freljord monument line — more poros, and a little culture besides.",
  iceWroughtSpire: "The Freljord monument line — more poros, and a wider culture ceiling.",
  frozenWatcher: "The Freljord monument line at its end — poros, True Ice, and a lift to everything.",
  shimmerRefinery: "Turns Coalgas and mana into Shimmer, and gives it somewhere to sit.",
  hexcreteBastion: "Deep storage for everything the Sump and the refineries produce.",
  hallOfHeroes: "Somewhere to hold the Renown your deeds earn.",
  petricite: "Demacian stone steadies the land, and everything the settlement produces.",
  shrine: "Devotion and a ceiling for it — and pilgrims bring stories, which is culture.",
  sanctum: "Every acolyte's devotion counts for more.",
  marus: "Devotion at scale, needing no workers, and a ceiling to match."
};

// v0.48 §4 — eight per-copy constants that were literals at their point of use and
// prose at their point of display. Now fields, read by both.
const FIELDS = {
  bardsHearth: "audience: 0.05",
  poroPasture: "eatCut: 0.003, eatCutLimit: 0.5",
  tradeDock: "tradeBoost: 0.02",
  workshop: "craftBoost: 0.06",
  hunterLodge: "campBoost: 0.15",
  chembarrel: "sumpBoost: 0.25",
  hexgateBuilding: "tradeBoost: 0.12"
};

function valueEnd(text, i) {
  let depth = 0, q = null;
  for (; i < text.length; i++) {
    const c = text[i], p = text[i - 1];
    if (q) { if (c === q && p !== "\\") q = null; continue; }
    if (c === "/" && text[i + 1] === "/") { i = text.indexOf("\n", i); if (i < 0) break; continue; }
    if (c === '"' || c === "'") { q = c; continue; }
    if (c === "[" || c === "{" || c === "(") depth++;
    else if (c === "]" || c === "}" || c === ")") { if (depth === 0) return i; depth--; }
    else if (c === "," && depth === 0) return i;
  }
  throw new Error("no value end");
}
// End of the object literal that starts at `open` (index of its "{").
function objEnd(text, open) {
  let depth = 0, q = null;
  for (let i = open; i < text.length; i++) {
    const c = text[i], p = text[i - 1];
    if (q) { if (c === q && p !== "\\") q = null; continue; }
    if (c === "/" && text[i + 1] === "/") { i = text.indexOf("\n", i); if (i < 0) break; continue; }
    if (c === '"' || c === "'") { q = c; continue; }
    if (c === "{" || c === "[" || c === "(") depth++;
    else if (c === "}" || c === "]" || c === ")") { depth--; if (depth === 0) return i; }
  }
  throw new Error("unbalanced object");
}

const a = src.indexOf("var BUILDINGS = [");
const b = src.indexOf("\nvar JOBS");
let body = src.slice(a, b);
let n = 0, missing = [];
for (const id of Object.keys(EFFECT)) {
  const anchor = body.indexOf('{ id: "' + id + '",');
  if (anchor < 0) { missing.push(id); continue; }
  const end = objEnd(body, anchor);
  const ek = body.indexOf("effect:", anchor);
  if (ek < 0 || ek > end) { missing.push(id + " (no effect)"); continue; }
  const ve = valueEnd(body, ek + 7);
  body = body.slice(0, ek) + "effect: " + JSON.stringify(EFFECT[id]) + body.slice(ve);
  n++;
  if (FIELDS[id]) {
    const e2 = objEnd(body, body.indexOf('{ id: "' + id + '",'));
    body = body.slice(0, e2).replace(/\s*$/, "") + ",\n    " + FIELDS[id] + " " + body.slice(e2);
  }
}
src = src.slice(0, a) + body + src.slice(b);
fs.writeFileSync(FILE, src);
console.log("rewrote", n, "building effect strings;", Object.keys(FIELDS).length, "field additions");
if (missing.length) { console.log("MISSING: " + missing.join(", ")); process.exit(1); }
