// v0.48 §3 — the prose split. 38 TECHS + 74 UPGRADES + 5 WTECHS = 117 strings.
// Each entry: [loreValue, effectValue]. A string literal is emitted as JSON; an
// object {raw:"..."} is emitted verbatim so the generated-prose helpers survive.
// null means "this entry genuinely has no content for that zone" -> field omitted.
const R = (s) => ({ raw: s });

export const TECHS = {
  // ---- drift note: the old desc claimed "unlocks the Academy". The Academy moved
  // behind The Scriptorium in v0.47 Part 4.1 and the string was never updated.
  almanac: ["Chart the seasons — when to sow, when to hold, and when the frost is only pretending to leave.",
            "Reveals the calendar and the turn of the seasons."],
  cultivation: ["Rows, seasons, and a reason to stay.", "Provisions production +10%."],
  // ---- drift note: the old desc claimed "Unlocks the Storehouse". The Storehouse is
  // gated on Cultivation, not Woodcraft.
  woodcraft: ["Timber stops being something you drag and becomes something you shape.",
              "Reveals Support Beams as a material."],
  logistics: ["Somebody finally wrote down how far it is to anywhere.",
              "Opens THE WILDS. Wanderers generate Vigor, which expeditions spend."],
  songcraft: ["The settlement starts remembering itself in song.", "Culture becomes a resource."],
  mining: ["Follow the seam, and stop apologising for the hole.", "Ore and Stone Slabs become resources."],
  trade: ["Caravans to Piltover, the Freljord, Bilgewater — and Noxus, if you dare.", "Opens TRADE."],
  smelting: ["Ore is only a rumour of metal until something gets hot enough.", "Steel becomes a resource."],
  masquerade: ["A jester's caravan has been sighted, and nobody saw it arrive.",
               "A painted box may now appear at the treeline — rarer than honeyfruit, and nobody put it there."],
  abyss: ["Map the passes to the Howling Abyss. Something fluffy lives there.",
          "A Gromp hunt may now bring a stray poro home."],
  yordle: ["Yordles do not explain their machines. They hand them over, working, and change the subject.", null],
  hextech: ["Piltover's secret, reverse-engineered from imported crystals.", "Home-grown Hextech Crystals at last."],
  drakeLore: ["The elemental drakes have returned to the wilds.", "Renown cap +60."],
  petricite: ["Stone that drinks magic, cut by people who resent being impressed.", null],
  voidStudies: ["Something ancient stirs beneath the river.", "Renown cap +80."],
  ritesOfTargon: ["The songs all point the same direction: a mountain that touches the stars.", "Opens MOUNT TARGON."],
  callToArms: ["Word of your settlement has reached names you know from songs.",
               "Opens CHAMPIONS — heroes answer settlements worth answering."],
  sparks: ["Your Piltovan friend keeps talking about home.", null],
  chemtech: ["The Sump has a second export, and it hisses.", null],
  hexcore: ["What if the crystals aren't storage, but seeds?", null],
  // ---- drift note: the old desc promised "the Foundry Overseer & Hexcrystal Warden
  // posts for champions". No such feature exists anywhere in the file.
  deepWorks: ["Beneath the foundries, the real work begins.", null],
  // ---- drift note: same, "the Void Expedition Leader post".
  icathia: ["Where the world was broken, something waits.", null],
  championsRegimen: ["Somebody has to organise the heroes, and it is never the heroes.", null],
  deepCartography: ["Maps of places the maps did not have.", null],
  refinedMetallurgy: ["The difference between iron and steel, written down at last.", null],
  hexdraulics: ["Water, pressure, and a crystal that will not admit which it is.", null],
  sumpEcology: ["Things live down there. Some of them are worth catching.", null],
  progressDay: ["Piltover's holiday, exported.", null],
  chemBaronAccords: ["An arrangement nobody signed and everybody honours.", null],
  gloriousEvolution: ["The machine herald has a proposal, and it is only partly about you.", null],
  atlasGauntlets: ["Undercity engineering at its least subtle.", null],
  hexgate: ["Two cities, one doorway, an enormous amount of paperwork.", null],
  greyReclamation: ["You cannot lift the Grey. You can, it turns out, make it work.", null],
  voidglassOptics: ["Glass that shows you the sky it came from.", null],
  scriptorium: ["Someone has to keep the copies straight, and then keep the copies of the copies.", null],
  carpentry: ["Joints that hold without rope.", null],
  watchersBelow: ["The Freljord has been keeping something down there, and Icathia has been keeping the same thing.", null],
  kindling: ["Heat kept is heat not spent.", null]
};

export const WTECHS = {
  solariHymn: ["Sung at dawn, in harmony, whether anyone feels like it or not.", "Devotion production +25%."],
  ritesOfInsight: ["The Aspects see far; the faithful learn to look.", "Knowledge production +10%."],
  sunAltar: ["Every shrine becomes a place people gather at dawn.",
             "Each Shrine of the Solari grants +0.5 morale, and +0.1 more per Altar tier."],
  solariAltar: ["A vessel worthy of what it holds.", "All devotion caps doubled."],
  convergence: ["The mountain answers.",
                "+1% to all production per √Worship — about +7% at Era 3, +44% at a million, ceiling +1000%."]
};

export const UPGRADES = {
  runicAttunement: ["The wells were always singing. Somebody finally learned the key.", "Mana Wells +50%."],
  ironPlows: ["Demacian iron, and a furrow that stays where you put it.", "Farmers +30%."],

  sharpenedAxes: ["A whetstone, and the discovery that it matters.", R('axeDesc("sharpenedAxes")')],
  ironAxes: ["Ironwood takes an edge the way stone takes rain — slowly, then permanently.", R('axeDesc("ironAxes")')],
  steelAxes: ["Steel does not care how old the tree is.", R('axeDesc("steelAxes")')],
  hexsteelAxes: ["The haft hums. Nobody has asked it to stop.", R('axeDesc("hexsteelAxes")')],
  atlasAxes: ["Undercity leverage, applied to a treeline.", R('axeDesc("atlasAxes")')],
  voidsteelAxes: ["The cut closes a moment after you finish it. Best not to watch.", R('axeDesc("voidsteelAxes")')],

  reinforcedSaw: ["Two hands, one blade, and a frame that stops it wandering.", R('sawDesc("reinforcedSaw")')],
  steelSaw: ["Teeth that stay teeth.", R('sawDesc("steelSaw")')],
  hexsteelSaw: ["It finishes the cut slightly before you do.", R('sawDesc("hexsteelSaw")')],
  atlasSaw: ["Geared, braced, and utterly unbothered.", R('sawDesc("atlasSaw")')],
  voidsteelSaw: ["The sawdust does not settle so much as decline to.", R('sawDesc("voidsteelSaw")')],

  zauniteDrills: ["Zaun sells the drill, the bits, and the replacement bits.",
                  "Every Mine's miner bonus rises 20% → 25%. Ore stays one category; this widens it."],
  arcaneFocus: ["A lens for something that was never light.", "+4 mana per channel, Arcanists +50%."],
  bilgewaterContracts: ["Signed in three places, one of them a thumbprint.", "All gold production +25%."],
  ironwoodShelters: ["Ironwood does not rot, and does not argue about it.",
                     R('ratioEffect("shelter", "ironwoodShelters")')],
  trueIceCellars: ["True Ice keeps a cellar honest through a Freljord summer.", "Wanderers eat 20% less."],
  reinforcedStorehouses: ["Gear-braced beams and doubled lofts.", "Storehouse capacity +75%."],
  expandedStores: ["Every loft doubled, every cellar dug deeper.", "Masonry I — all material storage ×1.75."],
  ironboundStores: ["Steel-strapped, and a lasting disappointment to rats.", "Masonry II — all material storage ×1.8."],
  hexRunedStores: ["The runes fold space, slightly, politely.", "Masonry III — all material storage ×2."],
  chemtechSilos: ["Pressurized, sealed, and probably fine.", "Masonry IV — all material storage ×2."],
  voidwardStores: ["Storage warded against the thing storage attracts.", "Masonry V — all material storage ×1.75."],

  cataloguing: ["Every scroll gets a shelf, every shelf gets a ledger.", R('scholarEffect("cataloguing", "I")')],
  crossReferencing: ["The ledgers start citing each other.", R('scholarEffect("crossReferencing", "II")')],
  greatIndex: ["One catalogue to find them all.", R('scholarEffect("greatIndex", "III")')],
  annotatedIndex: ["Every citation now cites its own citations.", R('scholarEffect("annotatedIndex", "IV")')],
  livingLibrary: ["The catalogue has started making suggestions.", R('scholarEffect("livingLibrary", "V")')],

  standingOrders: ["Drill happens whether or not anyone is watching.", "Champion training costs 25% less Renown."],
  surveyedApproaches: ["Knowing the way is most of the walk.", "Every expedition costs 15% less Vigor."],
  keepingTheRolls: ["The songs were always going to need the names anyway.",
                    "Unlocks the Census — every wanderer gets a name on a page, a trade beside it, and a rank that climbs."],
  sumpVentilation: ["Air moves, so the crews can. The Sump was never short of ore — only of people willing to stay in it.",
                    "Every Quarry's miner bonus rises 35% → 40%."],
  seasonedTimberworks: ["Cut, stacked, and left alone for a season. Impatience is the expensive part.",
                        "All timber production +25%."],
  hexresonance: ["Tune the crystal to the leyline instead of fighting it.", "All mana production +25%."],
  piltovanCranes: ["Lift it once, properly.", "Scaffold craft cost 40 → 28 beams."],
  progressDayParade: ["Piltover's holiday, exported — and the floats are load-bearing.",
                      "Culture storage ×1.35, and every caravan costs 15% less culture to fit out."],
  chemBaronTithe: ["Nobody signed it. Everybody honours it.",
                   "Sump Mine, Coalgas Vent & Hexcrystal Quarry output +35% (into the same diminishing pool as the Chembarrels)."],
  atlasGauntletsUp: ["A bigger fist does not carry more comfort.",
                     "Material camp yields +50% — Krugs, the Sump Crawl, drakes and the Baron. Comforts are unaffected."],
  greyScrubbers: ["The Grey does not lift, but it can be made to filter.", "Every converter draws 25% less mana."],
  voidglassLenses: ["Targon taught you to look; Icathia taught you what to look through.",
                    "Celestial Observatories hold +50% more knowledge each."],
  hexcreteFrames: ["Poured, set, and indifferent to weather.", R('ratioEffect("shelter", "hexcreteFrames")')],
  voidwrightFrames: ["The joints do not age, which nobody enjoys thinking about.",
                     R('ratioEffect("shelter", "voidwrightFrames")')],
  hexboundJoinery: ["The beams hold themselves together now.", R('ratioEffect("storehouse", "hexboundJoinery")')],
  petriciteFrames: ["Petricite frames, cut to a standard nobody has to re-measure.",
                    R('ratioEffect("shelter", "petriciteFrames")')],
  stonecutGuild: ["The masons finally unionize.", R('ratioEffect("storehouse", "stonecutGuild")')],
  clockworkBellows: ["A bellows that never gets bored.", "Converter output (Forge, Refinery) +25%."],
  masterworkTools: ["Ornn-forged, grudgingly.",
                    "Farmers & Woodcutters +25%. Miners work the seam, not the tool — their gains come from the Mine and the Quarry."],
  hexCapacitors: ["Charge held is charge not chased.", "Crystal production +50%."],
  celestialCharts: ["The stars were keeping time all along. Somebody wrote it down.", "All production +10%."],

  caravanserai: ["A walled yard, a well, and somewhere to leave the animals — the road gets shorter when the stops get better.",
                 "Every caravan costs 40 less Vigor."],
  letterOfMarque: ["A seal that means the tolls are somebody else's problem.", "Every caravan costs 15 less Gold."],
  mintedCoin: ["A coin is a promise you can bite.", "All gold production +20%."],
  fourPartHarmony: ["The descant was somebody's idea and nobody will admit whose.",
                    "Bard's Hearths produce +25% culture each."],
  jessedHawks: ["A hawk will not carry ore.",
                "Comfort camp yields +25% — Wolves, Gromp and Raptors. Material camps are unaffected."],
  facetedCuts: ["The difference between a gem and a rock is a decision made once, correctly.", "Tinkerers +25%."],
  ironShodWheels: ["The road is the same length; the cart argues less.",
                   "Every expedition costs a further 10% less Vigor."],
  bankedCoals: ["A fire you never let die is a fire you never rebuild.", "Forge and Refinery output +15%."],
  pastureRotation: ["Move them before they eat the field, which they will.", "Poro Pastures produce 50% more poros."],
  tributeReliquaries: ["What the pit gives up is worth housing properly.", "Hextech Crystal production +25%."],
  continuousDraw: ["The line does not stop. It is only ever slowed.",
                   "Sump Mine, Coalgas Vent & Hexcrystal Quarry output +25% (into the same diminishing pool as the Chembarrels)."],
  standardHour: ["Zaun agreed on an hour, eventually, loudly.",
                 "Every cooldown and charge in the Wilds and on the roads runs 10% faster."],
  riverstoneTools: ["Edges knapped from the riverbed, before anyone thought to write it down.", "Transmute yields +15%."],
  trappersCraft: ["Snares, deadfalls, and patience.", "All camp yields +25%."],
  beastLore: ["The wilds keep habits, and habits can be read.", "All camp yields +25%."],
  masterOfTheHunt: ["Your hunters are the story other settlements tell.", "All camp yields +50%."],
  scribesGuild: ["A hall where the ink is always wet.", "Parchment craft yield +10%."],
  harvestRites: ["Drums, stew, and a reason.", "Unlocks Hold a Festival."],
  illuminators: ["Gold leaf on every capital.", "Tome craft yield +10%."],
  greatLibrary: ["Everything anyone remembered, in one room.", "Parchment & Tome craft yields +20%."],
  timberframeJoinery: ["Mortise, tenon, and a roof that holds.", "Unlocks the Longhouse."],
  slabCutting: ["Stone cut square instead of carried round.", "Unlocks the Cut Stone Slab craft and the Warehouse."],
  deepwaterDocks: ["Pilings sunk past the tideline.", "Unlocks the Harbor."],
  chemtechDistillation: ["Fractions, condensers, and a great deal of ventilation.", "Unlocks the Hextech Refinery."]
};
